name: Deploy JavaDoc
on:
  push:
    branches:
      - deploy-action

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Generate docs
        run: ./gradlew dokkaHtml

      - name: Copy to directory
        run: |
          mkdir public
          cp -a ./build/dokka/html/* public/
          touch ./public/.nojekyll
         
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.github_token }}
          publish_dir: ./public